- hosts: web
  become: true
  vars:
    image_name: ""

  tasks:
    - name: Update the system
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable and start Docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Delete previous container if it exists
      community.docker.docker_container:
        name: react_web
        state: absent
        force_kill: yes

    - name: Deploy ReactJS container
      community.docker.docker_container:
        name: react_web
        image: "{{ image_name }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "80:80"
